volumes:
  minio-data: { }

services:
  traefik:
    image: "traefik:v2.9"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web-imagestore.address=:80"
#      - "--entrypoints.web.address=:80"
# since the time is short, we were not able to get a reasonable domain to get certified for HTTPS
#      - "--entrypoints.websecure.address=:443"
#      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
#      - "--certificatesresolvers.myresolver.acme.email=mpdevilleres@gmail.com"
#      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  imagestore:
    build: .
    ports:
      - "8000:8000"
    environment:
      BUILD_TAG: local
      BUILD_COMMIT: unknown
      MINIO_ACCESS_KEY_ID: AKIAQASCRQW123FQWEBC
      MINIO_SECRET_ACCESS_KEY: W214erhio/WQE1fvdfhklserQWEEsu
      MINIO_REGION: us-east-1
      MINIO_BUCKET_NAME: image
      MINIO_ENDPOINT_URL: http://minio:9001
      MONGO_USERNAME: root
      MONGO_PASSWORD: d37Wem7t5rUMgQJ8m7WzWEqySpqbnAVx
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: image_db
      MONGO_COLLECTION: frames
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imagestore.rule=PathPrefix(`/`)"
      - "traefik.http.routers.imagestore.entrypoints=web-imagestore"
      - "traefik.http.routers.imagestore.service=imagestore"
      - "traefik.http.services.imagestore.loadbalancer.server.port=8000"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.imagestore.rule=Host(`${DOMAIN}`)"
#      - "traefik.http.routers.imagestore.entrypoints=websecure"
#      - "traefik.http.services.imagestore.loadbalancer.server.port=8000"
#      - "traefik.http.routers.imagestore.tls.certresolver=myresolver"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
#      - "traefik.http.routers.imagestore-http.rule=Host(`${DOMAIN}`)"
#      - "traefik.http.routers.imagestore-http.entrypoints=web"
#      - "traefik.http.routers.imagestore-http.middlewares=redirect-to-https"
    profiles:
      - local

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: d37Wem7t5rUMgQJ8m7WzWEqySpqbnAVx
      MONGO_INITDB_DATABASE: image_db
    volumes:
      - ./contrib/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    profiles:
      - local

  minio:
    build: ./contrib/minio
    environment:
      - MINIO_ROOT_USER=AKIAQASCRQW123FQWEBC
      - MINIO_ROOT_PASSWORD=W214erhio/WQE1fvdfhklserQWEEsu
    volumes:
      - minio-data:/data
    command: /usr/bin/minio server --address 0.0.0.0:9001 --console-address 0.0.0.0:9002 /data
    ports:
      - "9001:9001"
      - "9002:9002"
    profiles:
      - local
