volumes:
  minio-data: { }

services:
  imagestore:
    build: .
    ports:
      - "8000:8000"
    environment:
      BUILD_TAG: local
      BUILD_COMMIT: unknown
      MINIO_ACCESS_KEY_ID: AKIAQASCRQW123FQWEBC
      MINIO_SECRET_ACCESS_KEY: W214erhio/WQE1fvdfhklserQWEEsu
      MINIO_REGION: us-east-1
      MINIO_BUCKET_NAME: image
      MINIO_ENDPOINT_URL: http://minio:9001
      MONGO_USERNAME: root
      MONGO_PASSWORD: d37Wem7t5rUMgQJ8m7WzWEqySpqbnAVx
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: image_db
      MONGO_COLLECTION: frames

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: d37Wem7t5rUMgQJ8m7WzWEqySpqbnAVx
      MONGO_INITDB_DATABASE: image_db
    volumes:
      - ./contrib/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  minio:
    build: ./contrib/minio
    environment:
      - MINIO_ROOT_USER=AKIAQASCRQW123FQWEBC
      - MINIO_ROOT_PASSWORD=W214erhio/WQE1fvdfhklserQWEEsu
    volumes:
      - minio-data:/data
    command: /usr/bin/minio server --address 0.0.0.0:9001 --console-address 0.0.0.0:9002 /data
    ports:
      - "9001:9001"
      - "9002:9002"
